### ISSUE TITLE
AMQPConnectionError (worker.py)

### ISSUE THREAD

**Issue by technoplato** [technoplato/Clipper#1]
```(env) lustig@Michaels-Mac-Pro PyClipper % python worker.py```
```Traceback (most recent call last):
  File "worker.py", line 10, in <module>
    connection = pika.BlockingConnection(pika.ConnectionParameters(host="localhost"))
  File "/Users/lustig/Library/Mobile Documents/com~apple~CloudDocs/Development/HACKATHONS/PyClipper/env/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 359, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/Users/lustig/Library/Mobile Documents/com~apple~CloudDocs/Development/HACKATHONS/PyClipper/env/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
```

**Comment by technoplato** [comment]
Fixed by making sure RabbitMQ server was running. I used the docker command on their Download page:

`docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management`
